sequenceDiagram
    actor dev as Developer
    participant api as CookItUpAPI (.py)
    participant recipe_gen as Recipe Generator (.py)
    participant nutrition as Nutrition (.py)
    participant extract as Parse (.py)
    participant mongo_helper as Mongo Helper (.py)
    participant edamam as EDAMAM API


    dev->>+api: HTTP POST /generate_recipe <br> with ingredients
    api->>+recipe_gen: recipe_generation_function<br>(ingredients)
    alt Recipe Generated
        recipe_gen->>+nutrition: get_nutrition<br>(generated_ingredients)
        
        nutrition->>+extract: parse_ingredients(ingredients_list)
        extract-->>-nutrition: return ingredient_objects_list
        
        nutrition->>+mongo_helper: <br>get_ingredients_list_nutrition(ingredient)
        mongo_helper-->>-nutrition: return ingredients_with_nutrition and ingredients_to_search
        
        nutrition->>nutrition: <br>request_nutrition_from_api(ingredients_to_search)
        activate nutrition
        nutrition->>+edamam: HTTP GET /nutrition-data with ingredient string
        edamam-->>-nutrition: nutritional info response
        nutrition->>+extract: <br>parse_recipe_data<br>(response.json())
        extract-->>-nutrition: return parsed ingredients list
        deactivate nutrition

        nutrition->>mongo_helper: <br>mongo_helper.insert_many_ingredients(missing_ingredients_for_db)
        nutrition-->>-recipe_gen: nutrition data
        recipe_gen->>+mongo_helper: <br>insert_recipe(recipe)
        mongo_helper-->>-recipe_gen: return recipe_id for inserted recipe
        recipe_gen-->>-api: Generated recipe with<br>nutrition and recipe_id
        api-->>-dev: Return response to the client
    else Invalid Recipe
        activate api
        activate recipe_gen
        recipe_gen-->>api: Failed to generate recipe
        deactivate recipe_gen
        api-->>dev: Notify developer of failure
        deactivate api
    end
